const app = document.querySelector('#app');
const dialog = document.querySelector('#detail');
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = v => typeof v === 'number' ? `$${v.toFixed(2)}` : '—';
let data, phase = 'idle', completed = 0, selected = null, timer = null, fixed = new Set(), fixing = new Set(), fixTimers = new Set();
let entries = [];
let motionCleanup = () => {};
let reportView = false, selectedModel = null;
const inputFor = id => data.inputs.find(x => x.id === id);
const causeFor = id => data.causes.find(x => x.id === id);
const isFixed = r => r.status === 'regressed' && fixed.has(r.cause_id);
const unresolved = () => entries.filter(({r}) => r.status === 'regressed' && !isFixed(r));
function validate(d) {
 if (d?._format === 'ner' && d.ner && d.candidates?.length) return;
 if (!d || !d.repo || !d.baseline || !d.prompt || !Array.isArray(d.inputs) || !Array.isArray(d.candidates) || !Array.isArray(d.causes) || !d.pr) throw Error('The report is missing required fields.');
 if (!d.inputs.length || !d.candidates.length) throw Error('The report must include at least one input and model.');
 const ids = new Set(d.inputs.map(x=>x.id));
 d.candidates.forEach(c=>{if(!c.summary || !Array.isArray(c.results))throw Error('A model is missing its summary or results.');c.results.forEach(r=>{if(!ids.has(r.input_id))throw Error('A result references an unknown input.');if(r.status==='regressed'&&!d.causes.some(x=>x.id===r.cause_id))throw Error('A failed result has no matching cause.');});});
}
function normalizeNER(raw) {
 const pct = n => typeof n === 'number' ? `${(n*100).toFixed(1)}%` : '—';
 const costChange = typeof raw.baseline.cost_per_1k_calls_usd === 'number' && typeof raw.candidate.cost_per_1k_calls_usd === 'number'
   ? (raw.candidate.cost_per_1k_calls_usd / raw.baseline.cost_per_1k_calls_usd - 1) * 100 : null;
 const items = raw.items.map(item => ({
   id:item.input_id, text:item.text, verdict:item.verdict, tricky:item.tricky,
   baseline:item.baseline, candidate:item.candidate, regressions:item.regressions,
   improvements:item.improvements, intermittent_failures:item.intermittent_failures
 }));
 const count = status => items.filter(item => item.verdict === status).length;
 const baselineMs = raw.baseline.latency_p50_s * 1000, candidateMs = raw.candidate.latency_p50_s * 1000;
 const normalized = {
   _format:'ner', _note:`NER comparison · ${raw.baseline_file} → ${raw.candidate_file}`,
   run_id: raw.generated_at || 'Recorded report',
   repo:{name:`${String(raw.task).toUpperCase()} entity extraction`,call_site:'Baseline → candidate comparison'},
   baseline:{model:raw.baseline.model,retires_on:null,runs_per_input:raw.baseline.outputs / Math.max(1,raw.items.length),noise_rate:raw.candidate.unstable_inputs / Math.max(1,raw.items.length),cost_per_1k_calls_usd:raw.baseline.cost_per_1k_calls_usd,latency_p50_ms:baselineMs,latency_p95_ms:raw.baseline.latency_p95_s*1000,accuracy:raw.baseline.accuracy,accuracy_label:pct(raw.baseline.accuracy),accuracy_metric:raw.baseline.accuracy_metric,checks:raw.baseline.checks},
   inputs:items.map(item=>({id:item.id,text:item.text})), causes:[], pr:null, ner:{...raw,items},
   candidates:[{model:raw.candidate.model,provider:'Candidate',summary:{total:items.length,passed:count('SAME')+count('IMPROVED'),passed_after_fix:count('SAME')+count('IMPROVED'),cost_change_pct:costChange,cost_per_1k_calls_usd:raw.candidate.cost_per_1k_calls_usd,latency_p50_ms:candidateMs,latency_p95_ms:raw.candidate.latency_p95_s*1000,speed_vs_baseline:baselineMs/candidateMs,recommended:raw.ready_to_merge,accuracy:raw.candidate.accuracy,accuracy_label:pct(raw.candidate.accuracy),verdict_counts:raw.verdict_counts},results:items.map(item=>({input_id:item.id,status:item.verdict==='REGRESSED'?'regressed':item.verdict==='CHANGED'?'changed':item.verdict==='IMPROVED'?'improved':'pass',score:item.candidate.score_runs.reduce((a,b)=>a+b,0)/Math.max(1,item.candidate.score_runs.length),runs:{passed:item.candidate.score_runs.filter(x=>x===1).length,total:item.candidate.score_runs.length},baseline_output:item.baseline.output.join('\n'),output:item.candidate.output.join('\n'),cause_id:null,after_fix_output:null,ner_item:item}))}]
 };
 return normalized;
}
function renderVisualDashboard() {
 motionCleanup();
 const m=data.migration, final=m.final.candidate, initial=m.candidates.find(c=>c.model===m.chosen), cause=m.causes?.[0], edit=m.final.prompt_edit;
 selectedModel ||= m.chosen;
 const selected=m.candidates.find(c=>c.model===selectedModel)||initial;
 const total=m.comparison.inputs_compared;
 const stack=(counts)=>['SAME','IMPROVED','CHANGED','REGRESSED'].map(k=>`<span class="segment ${k.toLowerCase()}" style="flex:${counts?.[k]||0}" title="${counts?.[k]||0} ${k.toLowerCase()}"></span>`).join('');
 const rows=[{...m.baseline,isBaseline:true},...m.candidates];
 const numeric=v=>typeof v==='number'&&Number.isFinite(v);
 const maximum=key=>Math.max(0,...rows.map(r=>numeric(r[key])?r[key]:0));
 const cell=(value,format,max,kind)=>`<div class="table-metric ${numeric(value)?'':'missing'}"><strong>${numeric(value)?format(value):'—'}</strong><span class="mini-track ${kind}" aria-hidden="true">${numeric(value)?`<i style="width:${max>0?Math.min(100,Math.max(0,value/max*100)):0}%"></i>`:''}</span>${numeric(value)?'':'<small>Not available</small>'}</div>`;
 app.innerHTML=`<div class="dashboard-heading"><div><p class="eyebrow">MIGRATION OVERVIEW / ${esc(m.pr?.target_repo||m.task)}</p><h1>New model. Same expectations.</h1><p>Find what changed. See what’s ready to ship.</p></div><div class="heading-actions"><span class="ready-badge"><i></i>${m.final.ready_to_merge?'Ready for review':'Needs review'}</span><button class="text-button" id="full-report">Full report ↗</button></div></div>
 <div class="migration-route"><span class="route-caption">MODEL UPGRADE</span><strong>${esc(m.baseline.model)}</strong><span class="route-line"><i></i>→</span><strong>${esc(m.chosen)}</strong><span class="route-tag">Prompt repaired</span><span class="route-note">Recorded evaluation</span></div>
 <div class="visual-grid"><section class="viz-card model-chart comparison-table-card"><div class="viz-title"><div><p class="eyebrow">MODEL COMPARISON</p><h2>The trade-offs, side by side.</h2></div><span class="table-stage">Before prompt repair</span></div><div class="comparison-scroll"><table class="comparison-table"><caption class="sr-only">Baseline and candidate metrics before prompt repair. Missing values retain their column positions.</caption><thead><tr><th scope="col">Model<span>Baseline & candidates</span></th><th scope="col">Quality <em>↑</em><span>Entity F1 · higher is better</span></th><th scope="col">Cost <em>↓</em><span>USD / 1,000 calls</span></th><th scope="col">Speed <em>↓</em><span>Median response · seconds</span></th><th scope="col">Tail latency <em>↓</em><span>p95 · seconds</span></th><th scope="col">Regressions <em>↓</em><span>Inputs worse than baseline</span></th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.isBaseline?'baseline-row':r.model===selectedModel?'focused-row':''}"><th scope="row">${r.isBaseline?`<strong>${esc(r.model)}</strong>`:`<button class="model-select" data-model="${esc(r.model)}" aria-pressed="${r.model===selectedModel}">${esc(r.model)}</button>`}<span class="model-tag ${r.model===m.chosen?'chosen-tag':''}">${r.isBaseline?'Current model':r.model===m.chosen?'Selected for migration':'Alternative'}</span></th><td>${cell(r.accuracy,percent,1,'quality-bar')}</td><td>${cell(r.cost_per_1k_calls_usd,money,maximum('cost_per_1k_calls_usd'),'cost-bar')}</td><td>${cell(r.latency_p50_s,v=>v.toFixed(3),maximum('latency_p50_s'),'speed-bar')}</td><td>${cell(r.latency_p95_s,v=>v.toFixed(3),maximum('latency_p95_s'),'tail-bar')}</td><td>${r.isBaseline?'<span class="baseline-reference">Reference</span>':numeric(r.regressed)?`<span class="regression-pill ${r.regressed?'has-regressions':''}">${esc(r.regressed)} ${r.regressed===1?'input':'inputs'}</span>`:'<span class="baseline-reference">—<br>Not available</span>'}</td></tr>`).join('')}</tbody></table></div><div class="comparison-foot"><span>Bars share a scale within each column. Shorter cost and latency bars are better.</span><span>— Not supplied · space reserved</span></div></section>
 <section class="viz-card repair-chart"><div class="viz-title"><div><p class="eyebrow">REPAIR IMPACT</p><h2>One fix. The regression is gone.</h2></div><span class="repair-symbol">↗</span></div><div class="impact-number"><span>${esc(initial?.regressed??'—')}</span><span class="impact-arrow">→</span><strong>${esc(m.final.verdict_counts.REGRESSED)}</strong><small>regressions</small></div><div class="stack-row"><span>Before</span><div class="stack" aria-label="Before repair: ${esc(initial?.regressed)} regressions">${stack(initial?.verdict_counts)}</div></div><div class="stack-row"><span>After</span><div class="stack" aria-label="After repair: ${esc(m.final.verdict_counts.REGRESSED)} regressions">${stack(m.final.verdict_counts)}</div></div><div class="stack-legend"><span><i class="same"></i>Same</span><span><i class="improved"></i>Improved</span><span><i class="changed"></i>Changed</span><span><i class="regressed"></i>Regressed</span></div></section>
 <section class="viz-card evidence-card"><div class="viz-title"><div><p class="eyebrow">WHAT SWITCHYARD CAUGHT</p><h2>A small word. A wrong label.</h2></div><span class="pill">${esc(cause?.input_id||'Evidence')}</span></div><p class="evidence-quote">“${esc(cause?.text||'No input evidence supplied.')}”</p><div class="evidence-flow"><div><span class="demo-label">Before repair</span><div class="entity-list">${(cause?.candidate_output||[]).map(v=>`<span class="entity ${cause.baseline_output.includes(v)?'':'entity-bad'}">${esc(v)}</span>`).join('')}</div></div><span class="flow-arrow">→</span><div><span class="demo-label">After repair</span><div class="entity-list">${(m.comparison.items.find(i=>i.input_id===cause?.input_id)?.candidate.output||[]).map(v=>`<span class="entity">${esc(v)}</span>`).join('')}</div></div></div><details class="inline-details"><summary>What changed in the prompt?</summary><p>${esc(edit?.rationale||'No edit recorded.')}</p><div class="diff"><div class="removed">− ${esc(edit?.old_text)}</div><div class="added">+ ${esc(edit?.new_text)}</div></div></details></section>
 <section class="viz-card checks-card"><div class="viz-title"><div><p class="eyebrow">FINAL EVALUATION</p><h2>Every input, at a glance.</h2></div><span class="chart-unit">${total} inputs</span></div><div class="result-mosaic">${data.candidates[0].results.map((r,i)=>`<button class="mosaic-cell ${r.status}" data-result="${i}" aria-label="Input ${i+1}: ${esc(r.ner_item.verdict)}" title="${esc(r.input_id)} · ${esc(r.ner_item.verdict)}">${r.status==='changed'?'≈':r.status==='improved'?'↑':r.status==='regressed'?'!':'·'}</button>`).join('')}</div><p class="mosaic-caption">${esc(m.final.verdict_counts.REGRESSED)} regressed · ${esc(m.final.verdict_counts.IMPROVED)} improved · ${esc(m.final.verdict_counts.CHANGED)} changed</p><p class="chart-caption">Click any square to inspect its output. Same means unchanged, not necessarily error-free.</p><div class="quality-summary"><span>Final extraction quality</span><strong>${percent(final.accuracy)}</strong><span class="quality-delta">${((final.accuracy-m.baseline.accuracy)*100).toFixed(1)} pp above baseline</span></div></section></div>
 <section class="delivery-strip"><div class="delivery-icon">⑂</div><div><h2>${m.final.ready_to_merge?'Migration ready for your review':'Migration needs review'}</h2><p>Model upgrade + prompt repair in one proposed code change.</p></div><button class="button primary" id="view-diff">Review code change ↗</button></section><div class="dashboard-foot"><span>Trade-off: ${final.latency_p50_s>m.baseline.latency_p50_s?'slower':'faster'} median response · ${final.cost_per_1k_calls_usd==null?'candidate cost unavailable':'cost in full report'} · ${final.unstable_inputs} unstable inputs</span><span>Recorded results · no live calls or published PR</span></div>`;
 app.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{selectedModel=b.dataset.model;render();});
 app.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>openDetail(0,Number(b.dataset.result)));
 app.querySelector('#full-report').onclick=()=>{reportView=true;phase='complete';completed=entries.length;render();};
 app.querySelector('#view-diff').onclick=()=>{dialog.innerHTML=`<div class="detail-head"><div><p class="eyebrow">PROPOSED CODE CHANGE</p><h2 id="detail-title">Review the migration</h2></div><button class="close" aria-label="Close details">×</button></div><div class="detail-body"><p>${esc(m.pr?.target_path)}</p><pre class="diff code-diff">${esc(m.pr?.diff||'No diff supplied.')}</pre><p class="provider">Recorded proposal. No published PR link supplied.</p></div>`;dialog.querySelector('.close').onclick=()=>dialog.close();dialog.showModal();};
 installDashboardMotion(m);
}
function installDashboardMotion(m) {
 const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');
 const heading=app.querySelector('.dashboard-heading');
 heading.classList.add('cinema-hero');
 heading.innerHTML=`<div class="hero-copy"><p class="hero-kicker">Switchyard / Model migration</p><h1>Move forward.<br><span>Keep what works.</span></h1><p class="hero-description">A new model. A precise repair.<br>Every change, backed by an evaluation.</p><div class="hero-actions"><button class="button primary" id="jump-comparison">Explore the results ↓</button><button class="text-button" id="full-report">Full report ↗</button></div></div><div class="model-stage" aria-label="Migration from ${esc(m.baseline.model)} to ${esc(m.chosen)}"><div class="metal-word" aria-hidden="true">SHIFT</div><div class="stage-halo" aria-hidden="true"></div><div class="model-object model-old"><span class="object-caption">CURRENT MODEL</span><strong>${esc(m.baseline.model)}</strong><div class="chip-traces" aria-hidden="true"></div><span class="object-foot">Baseline behavior</span></div><div class="model-object model-new"><span class="object-caption">SELECTED UPGRADE</span><strong>${esc(m.chosen)}</strong><div class="chip-traces" aria-hidden="true"></div><span class="object-foot">${m.final.ready_to_merge?'Ready for review':'Needs review'} <i></i></span></div><div class="stage-caption">${esc(m.pr?.target_repo||m.task)} <span>·</span> Recorded migration</div></div>`;
 app.querySelector('.migration-route').remove();
 const comparison=app.querySelector('.comparison-table-card');comparison.id='model-comparison';
 heading.querySelector('#jump-comparison').onclick=()=>comparison.scrollIntoView({behavior:reduce.matches?'instant':'smooth',block:'start'});
 heading.querySelector('#full-report').onclick=()=>{reportView=true;phase='complete';completed=entries.length;render();};
 const cause=m.causes?.[0], edit=m.final.prompt_edit;
 const evidence=app.querySelector('.evidence-card'), impact=app.querySelector('.repair-chart');
 if(cause && edit && evidence && impact){
 const corrected=m.comparison.items.find(i=>i.input_id===cause.input_id)?.candidate.output||[];
 const entityList=(values,bad=false)=>values.map(v=>`<span class="entity ${bad&&!cause.baseline_output.includes(v)?'entity-bad':''}">${esc(v)}</span>`).join('');
 const addition=edit.new_text?.startsWith(edit.old_text)?edit.new_text.slice(edit.old_text.length).replace(/^[.\s]+/,''):edit.new_text;
 const section=document.createElement('section');section.className='scroll-repair';section.setAttribute('aria-label','Recorded repair walkthrough');
 section.innerHTML=`<div class="repair-sticky"><div class="repair-anchor"><p class="eyebrow">FOLLOW THE REPAIR</p><h2>Same sentence.<br>A better interpretation.</h2><p class="anchored-quote">“${esc(cause.text)}”</p><div class="anchor-baseline"><span class="demo-label">Expected extraction</span><div class="entity-list">${entityList(cause.baseline_output)}</div></div><nav class="repair-stages" aria-label="Repair stages">${['Detect','Repair','Verify'].map((name,i)=>`<button data-repair-step="${i}"><span>0${i+1}</span>${name}</button>`).join('')}</nav><p class="scroll-cue">↓ Scroll to follow the recorded repair</p></div><div class="repair-scenes"><article class="repair-scene" data-scene="0"><span class="scene-number">01 / DETECT</span><h3>The upgrade adds a wrong label.</h3><div class="entity-list">${entityList(cause.candidate_output,true)}</div><p>${esc(cause.evidence?.join(' · '))}</p><span class="pill warn">Regression detected</span></article><article class="repair-scene" data-scene="1"><span class="scene-number">02 / REPAIR</span><h3>Clarify the instruction.</h3><p class="scene-component">${esc(edit.component)}</p><blockquote>${esc(addition)}</blockquote><details><summary>Inspect the complete prompt edit</summary><div class="diff"><div class="removed">− ${esc(edit.old_text)}</div><div class="added">+ ${esc(edit.new_text)}</div></div></details></article><article class="repair-scene" data-scene="2"><span class="scene-number">03 / VERIFY</span><h3>Retested with the repaired prompt.</h3><div class="entity-list">${entityList(corrected)}</div><div class="impact-slot"></div></article></div><div class="scroll-track" aria-hidden="true"><i></i></div></div>`;
 evidence.replaceWith(section);section.querySelector('.impact-slot').append(impact);
 impact.querySelector('.viz-title').remove();
 }
 
 const observer=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('motion-visible');observer.unobserve(item.target);}}),{threshold:0.12});
 for(const selector of ['.comparison-table-card','.checks-card','.delivery-strip']){const el=app.querySelector(selector);if(el){el.classList.add('motion-ready');observer.observe(el);}}
 app.querySelectorAll('.mosaic-cell').forEach((el,i)=>el.style.setProperty('--reveal-delay',`${i*22}ms`));
 const section=app.querySelector('.scroll-repair');let frame=0,active=-1;
 function setScene(index){if(active===index)return;active=index;section.querySelectorAll('[data-scene]').forEach((el,i)=>{el.classList.toggle('scene-active',i===index);el.inert=!reduce.matches&&i!==index;el.setAttribute('aria-hidden',String(!reduce.matches&&i!==index));});section.querySelectorAll('[data-repair-step]').forEach((el,i)=>{if(i===index)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});}
 function update(){frame=0;const heroProgress=reduce.matches?0:Math.min(1,Math.max(0,-heading.getBoundingClientRect().top/heading.offsetHeight));heading.style.setProperty('--hero-p',heroProgress);if(!section)return;const rect=section.getBoundingClientRect(),sticky=section.firstElementChild;const distance=Math.max(1,section.offsetHeight-sticky.offsetHeight);const progress=Math.min(1,Math.max(0,((parseFloat(getComputedStyle(sticky).top)||0)-rect.top)/distance));setScene(Math.min(2,Math.floor(progress*3)));section.querySelector('.scroll-track i').style.transform=`scaleX(${progress})`;}
 function onScroll(){if(!frame)frame=requestAnimationFrame(update);}
 function preference(){active=-1;update();}
 if(section){section.querySelectorAll('[data-repair-step]').forEach((button,i)=>button.onclick=()=>{if(reduce.matches){section.querySelector(`[data-scene="${i}"]`).scrollIntoView({block:'center'});return;}const distance=Math.max(1,section.offsetHeight-section.firstElementChild.offsetHeight);window.scrollTo({top:window.scrollY+section.getBoundingClientRect().top-(parseFloat(getComputedStyle(section.firstElementChild).top)||0)+distance*(i===0?0:i===1?.5:1),behavior:'smooth'});});window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);reduce.addEventListener('change',preference);update();}
 motionCleanup=()=>{observer.disconnect();cancelAnimationFrame(frame);window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onScroll);reduce.removeEventListener('change',preference);};
}
function normalizeMigration(raw) {
 if (!raw.final || !raw.comparison?.items?.length) throw Error('Migration report needs final results and a per-input comparison.');
 const result = normalizeNER(raw.comparison);
 result.migration = raw;
 result.run_id = raw.finished || raw.started || 'Recorded report';
 result.repo = {name:raw.pr?.target_repo || `${raw.task} migration`,call_site:raw.pr?.target_path || 'Model migration'};
 result._note = 'Complete migration report · Candidate selection → prompt repair → final evaluation.';
 return result;
}
const percent = v => typeof v === 'number' ? `${(v * 100).toFixed(1)}%` : '—';
const seconds = v => typeof v === 'number' ? `${v.toFixed(3)} s` : '—';
function renderMigration() {
 const m=data.migration;
 const counts = v => ['REGRESSED','IMPROVED','CHANGED','SAME'].map(key=>`${v?.[key]??0} ${key.toLowerCase()}`).join(' · ');
 const cards=app.querySelector('.cards');
 cards.insertAdjacentHTML('beforebegin', `<section class="migration-section"><p class="eyebrow">01 / Candidate selection · before repair</p><div class="cards">${m.candidates.map(c=>`<article class="card ${c.model===m.chosen?'recommended':''}"><div class="card-head"><div><h3>${esc(c.model)}</h3><div class="provider">Rank ${esc(c.rank??'—')}</div></div>${c.model===m.chosen?'<span class="recommend">SELECTED</span>':''}</div><div class="quality"><strong>${percent(c.accuracy)}</strong><small>entity F1</small></div><p class="provider">${esc(counts(c.verdict_counts))}</p><div class="metrics"><div class="metric"><label>Median response</label><strong>${seconds(c.latency_p50_s)}</strong><small>${esc(c.unstable_inputs)} unstable inputs</small></div><div class="metric"><label>Cost / 1,000 calls</label><strong>${money(c.cost_per_1k_calls_usd)}</strong><small>${c.cost_per_1k_calls_usd==null?'Not supplied in report':'Recorded cost'}</small></div></div></article>`).join('')}</div><p class="provider">Baseline ${esc(m.baseline.model)} · ${percent(m.baseline.accuracy)} entity F1 · ${seconds(m.baseline.latency_p50_s)} median · ${money(m.baseline.cost_per_1k_calls_usd)} / 1,000 calls. Initial per-input reports are referenced but not included.</p></section>
 <section class="panel migration-section"><div class="panel-heading"><div><p class="eyebrow">02 / Diagnose & repair</p><h2>Recorded prompt repairs</h2><p>Evidence and accepted edits from the migration run</p></div><span class="pill">${m.fix_attempts?.length??0} attempts</span></div><div class="repair-body">${(m.causes||[]).map(c=>`<details class="record" open><summary>${esc(c.input_id)} · ${esc(c.status)} cause</summary><p>${esc(c.text)}</p><div class="outputs"><div class="output"><label>BASELINE ENTITIES</label><p>${esc(c.baseline_output?.join('\n'))}</p></div><div class="output bad"><label>BEFORE REPAIR · ${esc(m.chosen)}</label><p>${esc(c.candidate_output?.join('\n'))}</p></div></div><p>${esc(c.evidence?.join(' · '))}</p><p class="provider">Confirmed component: ${esc(c.confirmed_component||'Not confirmed')}</p>${(c.suspects||[]).map(s=>`<p class="provider">${esc(s.component)} · suspicion score ${esc(s.score)} · ${s.editable?'editable':'not editable'}</p>`).join('')}</details>`).join('')}${(m.fix_attempts||[]).map(f=>`<details class="record" open><summary>Attempt ${esc(f.attempt)} · ${esc(f.outcome)}</summary><p class="provider">${esc(f.edit?.component)}</p><div class="diff"><div class="removed">− ${esc(f.edit?.old_text)}</div><div class="added">+ ${esc(f.edit?.new_text)}</div></div><p>${esc(f.edit?.rationale)}</p><p class="provider">${esc(counts(f.verdict_counts))}</p><span class="pill ${f.accepted?'':'warn'}">${f.accepted?'Accepted in recorded run':'Not accepted'}</span></details>`).join('')||'<p>No repair records supplied.</p>'}</div></section><p class="eyebrow">03 / Final evaluation · after repair</p>`);
 app.querySelector('#tests-title').textContent='Per-input results after repair';
 app.querySelector('.row-label small').textContent=`${data.ner.verdict_counts.REGRESSED??0} regressed after repair`;
 const banner=app.querySelector('.pr-banner');
 banner.querySelector('h2').textContent=m.final.ready_to_merge?'✓ Migration ready for review':'Migration needs review';
 banner.querySelector('.provider').textContent='Readiness reported by the evaluation';
 if(m.pr) banner.insertAdjacentHTML('afterend', `<section class="panel migration-section pr-section"><div class="panel-heading"><div><p class="eyebrow">04 / Proposed code change</p><h2>Pull request preview</h2><p>${esc(m.pr.title)}</p></div></div><div class="repair-body"><p class="provider">${esc(m.pr.target_path)}</p><details class="record"><summary>View proposed diff</summary><pre class="diff code-diff">${esc(m.pr.diff||'No diff supplied.')}</pre></details><p class="provider">${safeURL(m.pr.url)?`<a href="${esc(safeURL(m.pr.url))}" target="_blank" rel="noopener noreferrer">Open pull request ↗</a>`:'No published PR link is included. This is the recorded proposal.'}</p></div></section>`);
}
function render() {
 app.classList.toggle('full-report-view',reportView);
 if(reportView)motionCleanup();
 if(data.migration && !reportView){renderVisualDashboard();return;}
 const total=entries.length, done=phase==='complete', remaining=unresolved().length;
 const end=Date.parse(data.baseline.retires_on), reference=Date.parse(data.run_id);
 const days=Number.isFinite(end)&&Number.isFinite(reference)?Math.max(0,Math.ceil((end-reference)/86400000)):null;
 const retirement=days===null?'':`<span class="pill warn">${days} days to retirement at report time</span>`;
 app.innerHTML=`<section class="intro"><div><p class="eyebrow">Migration report / ${esc(data.repo.call_site)}</p><h1>${esc(data.repo.name)}</h1><div class="subline"><span>Baseline</span><strong>${esc(data.baseline.model)}</strong>${retirement}</div></div><div class="actions"><button class="button" id="reset">↺ Reset</button><button class="button primary" id="run" ${phase==='running'?'disabled':''}>${phase==='running'?'Running replay…':phase==='complete'?'↻ Replay run':'▶ Run comparison'}</button></div></section>
 ${data._note?`<div class="sample"><span>◈</span><span>${esc(data._note)} This dashboard replays recorded results; no live model calls.</span></div>`:''}
 <section class="cards" aria-label="Model comparison">${data.candidates.map((c,ci)=>{
 const repaired=c.results.filter(isFixed).length;
 const passed=done?c.summary.passed+repaired:c.summary.passed;
 const cost=c.summary.cost_change_pct;
 return `<article class="card ${c.summary.recommended?'recommended':''}"><div class="card-head"><div><h3>${esc(c.model)}</h3><div class="provider">${esc(c.provider)}</div></div>${c.summary.recommended?'<span class="recommend">RECOMMENDED</span>':''}</div><div class="quality"><strong>${data._format==='ner'?esc(c.summary.accuracy_label):esc(passed)}</strong><small>${data._format==='ner'?'entity F1':`/ ${esc(c.summary.total)}`}</small><span>${data._format==='ner'?`vs ${data.baseline.accuracy_label} baseline · ${esc(c.summary.verdict_counts.REGRESSED??0)} regressed`:repaired?'passed after fixes':'recorded passes'}</span></div><div class="quality-track"><i style="width:${Math.min(100,Math.max(0,data._format==='ner'?c.summary.accuracy*100:passed/c.summary.total*100))}%"></i></div><div class="metrics"><div class="metric"><label>Cost / 1,000 calls</label><strong>${money(c.summary.cost_per_1k_calls_usd)}</strong>${cost===null?'<small>Candidate cost unavailable</small>':`<span class="change">${cost>0?'+':''}${esc(cost.toFixed(1))}%</span>`}<small>Baseline ${money(data.baseline.cost_per_1k_calls_usd)}</small></div><div class="metric"><label>Median response</label><strong>${esc(Math.round(c.summary.latency_p50_ms))} ms</strong><small>${esc(c.summary.speed_vs_baseline.toFixed(2))}× baseline speed · p95 ${Math.round(c.summary.latency_p95_ms)} ms</small></div></div></article>`;
 }).join('')}</section>
 <section class="panel" aria-labelledby="tests-title"><div class="panel-heading"><div><h2 id="tests-title">Behavior across models</h2><p>${data.inputs.length} inputs · ${data.candidates.length} candidates · ${esc(data.baseline.runs_per_input)} runs per input</p></div><div class="progress-meta" role="status"><strong>${completed} / ${total}</strong><br>${phase==='idle'?'Ready to replay':phase==='running'?'Replaying results':'Comparison complete'}</div></div><div class="progress" role="progressbar" aria-label="Replay progress" aria-valuenow="${completed}" aria-valuemin="0" aria-valuemax="${total}"><i style="width:${completed/total*100}%"></i></div><div class="grid-body">${data.candidates.map((c,ci)=>`<div class="grid-row"><div class="row-label"><strong>${esc(c.model)}</strong><small>${c.results.filter(r=>r.status==='regressed'&&!isFixed(r)).length} flagged · ${c.results.filter(isFixed).length} fixed</small></div><div class="tiles">${c.results.map((r,ri)=>{
 const n=entries.findIndex(e=>e.ci===ci&&e.ri===ri), revealed=n<completed;
 const state=fixing.has(r.cause_id)&&r.status==='regressed'?'running':revealed?(isFixed(r)?'fixed':r.status):phase==='running'&&n===completed?'running':'pending';
 const label=state==='fixed'?'fixed':r.status==='changed'?'changed':r.status==='improved'?'improved':state;
 return `<button class="tile ${state}" data-ci="${ci}" data-ri="${ri}" ${revealed?'':'disabled'} title="${esc(r.input_id)} · ${label}" aria-label="${esc(c.model)}, input ${ri+1}, ${label}">${state==='fixed'?'✓':String(ri+1).padStart(2,'0')}</button>`;
 }).join('')}</div></div>`).join('')}</div><div class="legend">${data._format==='ner'?'<span><i class="dot pass"></i>Same</span><span><i class="dot improved"></i>Improved</span><span><i class="dot changed"></i>Changed</span><span><i class="dot regressed"></i>Regressed</span>':'<span><i class="dot pass"></i>Passed</span><span><i class="dot regressed"></i>Got worse</span><span><i class="dot fixed"></i>Fixed</span><span><i class="dot"></i>Pending</span>'}<span>Click a result to inspect the evidence</span></div></section>
 <div class="statusbar"><span>${done?(data._format==='ner'?`${data.ner.verdict_counts.REGRESSED??0} regressed · ${data.ner.verdict_counts.CHANGED??0} changed · ${data.ner.verdict_counts.IMPROVED??0} improved`:remaining?`${remaining} flagged results to review. Fixes apply to every result with the same cause.`:'All flagged results resolved.'): 'Run the comparison to reveal individual results.'}</span><span>${data._format==='ner'?`Candidate unstable inputs: ${esc(data.ner.candidate.unstable_inputs)} / ${esc(data.ner.inputs_compared)}`:`Baseline variation: ${esc(Math.round(data.baseline.noise_rate*100))}%`}</span></div>
 ${data._format==='ner'?`<section class="pr-banner ${data.ner.ready_to_merge?'':'merge-blocked'}" role="status"><div><h2><span class="pr-icon">${data.ner.ready_to_merge?'✓':'!'}</span>${data.ner.ready_to_merge?'Ready to merge':'Not ready to merge'}</h2><p>${esc(data.ner.verdict_counts.REGRESSED??0)} regression · ${esc(data.ner.verdict_counts.IMPROVED??0)} improved · ${esc(data.ner.verdict_counts.CHANGED??0)} changed · ${esc(data.ner.verdict_counts.SAME??0)} same</p><span class="pill">${esc(data.ner.inputs_compared)} inputs compared · ${esc(data.ner.candidate.unstable_inputs)} unstable candidate inputs</span></div><span class="provider">${data.ner.ready_to_merge?'All merge checks passed':'Review the regressed and changed examples'}</span></section>`:done&&remaining===0?`<section class="pr-banner" role="status"><div><h2><span class="pr-icon">⑂</span>Migration ready for review</h2><p>${esc(data.pr.title)}</p><span class="pill">${esc(data.pr.status)} · ${esc(data.pr.lines_changed)} lines changed</span></div>${safeURL(data.pr.url)?`<a class="button" href="${esc(safeURL(data.pr.url))}" target="_blank" rel="noopener noreferrer">Open pull request ↗</a>`:'<span class="provider">PR link not available in this report</span>'}</section>`:''}
 <footer><span>SWITCHYARD / Inspect. Repair. Migrate.</span><span>Report ${esc(data.run_id)} · Recorded replay</span></footer>`;
 if(data.migration) {renderMigration(); app.querySelector('.actions').insertAdjacentHTML('afterbegin','<button class="button" id="demo-view">← Dashboard</button>'); app.querySelector('#demo-view').onclick=()=>{clearTimers();reportView=false;render();};}
 document.querySelector('#run').onclick=start;
 document.querySelector('#reset').onclick=reset;
 app.querySelectorAll('[data-ci]').forEach(b=>b.onclick=()=>openDetail(+b.dataset.ci,+b.dataset.ri));
}
function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function clearTimers(){clearInterval(timer);timer=null;fixTimers.forEach(clearTimeout);fixTimers.clear();}
function reset(){clearTimers();phase='idle';completed=0;fixed.clear();fixing.clear();selected=null;dialog.close();render();}
function start(){reset();phase='running';render();const delay=15000/entries.length;timer=setInterval(()=>{completed++;if(completed>=entries.length){completed=entries.length;phase='complete';clearInterval(timer);timer=null;}render();if(dialog.open)drawDetail();},delay);}
function openDetail(ci,ri){selected={ci,ri};drawDetail();if(!dialog.open)dialog.showModal();}
function drawDetail(){
 if(!selected)return;
 const {ci,ri}=selected,c=data.candidates[ci],r=c.results[ri],input=inputFor(r.input_id),cause=causeFor(r.cause_id),repaired=isFixed(r),busy=fixing.has(r.cause_id);
 if(r.ner_item){const item=r.ner_item;const formatEntities=values=>values.length?values.map(esc).join('<br>'):'(no entities)';const formatErrors=errors=>errors.length?errors.map(error=>`<div class="error-item"><strong>${esc(error.type.replaceAll('_',' '))}</strong>${error.gold?` · expected ${esc(error.gold[0])}/${esc(error.gold[1])}`:''}${error.pred?` · found ${esc(error.pred[0])}/${esc(error.pred[1])}`:''}</div>`).join(''):'No errors recorded.';const itemScore=item.candidate.score_runs.map(value=>`${(value*100).toFixed(1)}%`).join(' · ');dialog.innerHTML=`<div class="detail-head"><div><p class="eyebrow">${esc(item.id)} · ${item.tricky?'Tricky input':'Standard input'}</p><h2 id="detail-title">${esc(item.verdict)}</h2></div><button class="close" aria-label="Close details">×</button></div><div class="detail-body"><h3>Input</h3><div class="input-text">${esc(item.text)}</div><h3>Extracted entities</h3><div class="outputs"><div class="output"><label>BASELINE · ${esc(data.baseline.model)}</label><p>${formatEntities(item.baseline.output)}</p><small>F1 across runs: ${item.baseline.score_runs.map(v=>`${(v*100).toFixed(1)}%`).join(' · ')}</small></div><div class="output ${item.verdict==='REGRESSED'?'bad':item.verdict==='IMPROVED'?'good':''}"><label>CANDIDATE · ${esc(data.candidates[ci].model)}</label><p>${formatEntities(item.candidate.output)}</p><small>F1 across runs: ${itemScore} · ${item.candidate.stable?'Stable':'Unstable'}</small></div></div><h3>Candidate errors</h3><div class="input-text">${formatErrors(item.candidate.errors)}</div>${item.baseline.errors.length?`<h3>Baseline errors</h3><div class="input-text">${formatErrors(item.baseline.errors)}</div>`:''}${item.intermittent_failures.length?`<h3>Intermittent failures</h3><div class="input-text">${formatErrors(item.intermittent_failures)}</div>`:''}<h3>Run verdict</h3><p>${esc(item.verdict)}${item.regressions.length?` · ${esc(item.regressions.length)} regression signal`:''}${item.improvements.length?` · ${esc(item.improvements.length)} improvement signal`:''}</p></div><div class="detail-bottom"><span>Evaluation details from the supplied report</span><button class="button" aria-label="Close details">Close</button></div>`;dialog.querySelectorAll('.close, .detail-bottom button').forEach(button=>button.onclick=()=>dialog.close());return;}
 dialog.innerHTML=`<div class="detail-head"><div><p class="eyebrow">${esc(c.model)} / ${esc(r.input_id)}</p><h2 id="detail-title">${esc(cause?(repaired?cause.fixed_title:cause.title):'Result details')}</h2></div><button class="close" aria-label="Close details">×</button></div><div class="detail-body"><div class="subline"><span class="pill">${esc(r.runs.passed)}/${esc(r.runs.total)} original runs passed</span>${cause?`<span class="pill warn">${esc(cause.check.startsWith('hard_check')?'Hard check · '+cause.check.split(':').slice(1).join(':').trim():'AI judge')}</span>`:''}${repaired?'<span class="pill">Fix replay complete</span>':''}</div><h3>Customer input</h3><div class="input-text">${esc(input.text)}</div><h3>Output comparison</h3><div class="outputs"><div class="output"><label>BASELINE · ${esc(data.baseline.model)}</label><p>${esc(r.baseline_output)}</p></div><div class="output ${repaired?'good':cause?'bad':''}"><label>${repaired?'AFTER FIX':'CANDIDATE'} · ${esc(c.model)}</label><p>${esc(repaired?(r.after_fix_output??'No revised output was supplied for this input. See the recorded retest summary below.'):r.output)}</p></div></div>${cause?`<h3>Why it changed</h3><p>${esc(cause.reason)}</p><h3>Suggested prompt change <span class="provider">· line ${esc(cause.line)}</span></h3><p class="provider">${esc(data.prompt.file)}</p><div class="diff"><div class="removed">− ${esc(cause.fix.old_line)}</div><div class="added">+ ${esc(cause.fix.new_line)}</div></div>${repaired?`<p>Recorded cause-level retest: <strong>${esc(cause.fix.retest.passed)}/${esc(cause.fix.retest.total)} passed</strong>. This is replayed evidence, not a new model run.</p>`:''}`:'<p>This result passed the recorded evaluation. No repair is attached.</p>'}</div><div class="detail-bottom"><span>${cause?'Applies to all flagged results linked to cause '+esc(cause.id):'Recorded score: '+esc(r.score)}</span>${cause?`<button class="button primary" id="fix" ${repaired||busy||phase!=='complete'?'disabled':''}>${repaired?'✓ Fix applied':busy?'Replaying retest…':phase!=='complete'?'Finish replay first':'Apply fix & replay retest'}</button>`:''}</div>`;
 dialog.querySelector('.close').onclick=()=>dialog.close();
 const button=dialog.querySelector('#fix');if(button)button.onclick=()=>applyFix(cause.id);
}
function applyFix(id){if(phase!=='complete'||fixing.has(id)||fixed.has(id))return;fixing.add(id);render();drawDetail();const handle=setTimeout(()=>{fixTimers.delete(handle);fixing.delete(id);fixed.add(id);render();drawDetail();},900);fixTimers.add(handle);}
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
try{const response=await fetch('./results.json',{cache:'no-store'});if(!response.ok)throw Error(`Could not load results.json (${response.status}).`);const raw=await response.json();data=raw?.comparison && Array.isArray(raw.candidates)?normalizeMigration(raw):raw?.task==='ner'?normalizeNER(raw):raw;validate(data);entries=data.candidates.flatMap((c,ci)=>c.results.map((r,ri)=>({r,ci,ri})));render();}catch(error){app.innerHTML=`<section class="error"><h1>Couldn’t open this report</h1><p>${esc(error.message)}</p><p>Serve this folder with a local web server and include a valid results.json. Opening index.html directly from Finder may prevent the browser from reading the JSON.</p></section>`;}
